language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - cd flaskapp
deploy:
  provider: heroku
  api_key: d94c868d-5c6d-46d1-b1ee-af304d17fefc
  app:
    master: applfor
